### ISSUE TITLE
bug: signTypedData using Coinbase Wallet not working

### ISSUE THREAD

**Issue by ceduarte25** [wevm/wagmi#4414]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

I am doing signing of EIP 712 message using Metamask and Coinbase wallet. I connected both using wagmi connectors as well. The signTypedData is working fine when I am on Metamask so I was expecting it will work on Coinbase as well. But when I am trying to sign on Coinbase, its given me this error:

UnknownRpcError: An unknown RPC error occurred.

Details: hashFuncMap[method] is not a function

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/new-wagmi-hys7ma?file=src%2Fwagmi.ts,src%2FApp.tsx,src%2Fmain.tsx

### Steps To Reproduce

1. Click connect with metamask
2. Click sign once connected, the metamask popup will show up with correct message data
3. Disconnect with metamask and connect with coinbase
4. Click sign once connected again, it will show the error

### What Wagmi package(s) are you using?

wagmi, @wagmi/connectors, @wagmi/core

### Wagmi Package(s) Version(s)

^2.12.31

### Viem Version

2.x

### Anything else?

When I am creating the stackblitz, I noticed that it's working fine on wagmi v2.0.0 and viem v2.0.0. When I tried upgrading it to the versions I am using, it starts failing.

**Comment by tmm** [comment]
Not able to reproduce against latest Wagmi version. This is [likely a Coinbase Wallet SDK bug](https://github.com/coinbase/coinbase-wallet-sdk/blob/8891097da975f8a1a51c144dc210b563f2f147ff/packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.ts#L445) and should be reported upstream if it occurs again.
